version: '2'
services:
  wildbeast:
    image: dougley/wildbeast
    environment:
      BOT_TOKEN:
      BOT_PREFIX:
      WILDBEAST_MASTERS:
      ARANGO_URI: http://arango:8529
      LAVA_NODES: '[{"host":"lavalink","port":80,"region":"us","password":"password"}'
    links:
    - arango:arango
    - lavalink:lavalink
  arango:
    image: arangodb:3.3.3
    environment:
      ARANGO_NO_AUTH: '1'
  lavalink:
    image: fredboat/lavalink:v2
    environment:
      LAVALINK_SERVER_BUFFER_DURATION_MS: '400'
      LAVALINK_SERVER_PASSWORD: password
      LAVALINK_SERVER_SOURCES_BANDCAMP: 'true'
      LAVALINK_SERVER_SOURCES_HTTP: 'true'
      LAVALINK_SERVER_SOURCES_LOCAL: 'false'
      LAVALINK_SERVER_SOURCES_MIXER: 'true'
      LAVALINK_SERVER_SOURCES_SOUNDCLOUD: 'true'
      LAVALINK_SERVER_SOURCES_TWITCH: 'true'
      LAVALINK_SERVER_SOURCES_VIMEO: 'true'
      LAVALINK_SERVER_SOURCES_YOUTUBE: 'true'
      LAVALINK_SERVER_WS_HOST: 0.0.0.0
      LAVALINK_SERVER_WS_PORT: '80'
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: '600'
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: '2333'